apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  namespace: django-app
  labels:
    type: local
    app: django-staticfiles
spec:
  storageClassName: ""
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
    - region us-east-1
    - allow-overwrite
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: django-eks-static-files
  


